### ISSUE TITLE
No model file 

### ISSUE THREAD

**Issue by ghost** [EmilStenstrom/json-tagger#1]
Looks like you took the model files for Swedish away recently. What's the reason for that? 

Awesome project btw!

Never mind, found the model files here: https://github.com/jwijffels/udpipe.models.ud.2.0/tree/master/inst/udpipe-ud-2.0-170801

**Comment by EmilStenstrom** [comment]
Yeah, I removed the Swedish version. I actually have no idea how people use this project, but I thought making it smaller, and having people download the models themselves, might make non-Swedes more eager to use the project.

What are you using the project for?
